---
title: "Certificaciones"
page-layout: full
title-block-style: none
comments: false
---

## Reconocimientos

::: {.grid}

::: {.g-col-12 .g-col-md-6}
::: {.card .border-info .mb-3}
::: {.card-body}

#### {{< fa trophy >}} Databricks MVP 2026 {.card-title style="margin-top: 0; color: #1a1a1a;"}

**Databricks** | Ago 2026

Reconocimiento de Databricks a quienes impulsan la comunidad de datos e IA a través de contenido técnico, charlas, meetups y trabajo open source.

[{{< fa external-link-alt >}} Ver Credencial](https://credentials.databricks.com/0125c7bb-d458-407f-82eb-3ecb9d54c5bb#acc.oFEt4JiI){.btn .btn-outline-info .btn-sm}

:::
:::
:::

:::

## Certificaciones

::: {.grid}

::: {.g-col-12 .g-col-md-6}
::: {.card .border-info .mb-3}
::: {.card-body}

#### {{< fa award >}} Data Engineer Professional {.card-title style="margin-top: 0; color: #1a1a1a;"}

**Databricks** | Oct 2025

Valida expertise avanzado en ETL, optimización de pipelines de datos, seguridad y gobernanza en la plataforma Databricks Lakehouse.

[{{< fa external-link-alt >}} Ver Credencial](https://credentials.databricks.com/64b8ff9e-7ff0-4213-a4af-4612ecf973a7){.btn .btn-outline-info .btn-sm}

:::
:::
:::

::: {.g-col-12 .g-col-md-6}
::: {.card .border-info .mb-3}
::: {.card-body}

#### {{< fa award >}} Data Engineer Associate {.card-title style="margin-top: 0; color: #1a1a1a;"}

**Databricks** | Ago 2025

Valida conocimiento fundacional de la plataforma Databricks Lakehouse, ELT con Spark SQL y Python, y procesamiento incremental de datos.

[{{< fa external-link-alt >}} Ver Credencial](https://credentials.databricks.com/4b91b7aa-d440-441a-8ebf-d933cc10ce48#acc.Qi3E78d9){.btn .btn-outline-info .btn-sm}

:::
:::
:::

:::
